# Generated by Django 4.2.25 on 2025-11-18 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_comentario_respuesta_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos_asignados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de cliente a técnico',
                'verbose_name_plural': 'Asignaciones de clientes a técnicos',
                'unique_together': {('tecnico', 'cliente')},
            },
        ),
    ]
