# Generated by Django 4.2.25 on 2025-11-18 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_asignacioncliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncliente',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacioncliente',
            name='tecnico',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
