# Generated by Django 4.2.25 on 2025-11-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_envio', models.CharField(choices=[('preparando', 'Preparando tu orden'), ('en_reparto', 'Entregada a la empresa de reparto')], default='preparando', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='tickets.ticket')),
            ],
        ),
    ]
