# Generated by Django 4.2.25 on 2025-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='actualizado_en',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Preparando tu orden'), ('despachado', 'Envío entregado a la empresa de reparto'), ('entregado', 'Entregado al cliente')], default='pendiente', max_length=20),
        ),
    ]
